"""
Curated resource directory for tryHimandsee Ministries.

Real, verified organizations serving Richmond and Henrico, Virginia.
This is the source of truth for the FastAPI preview stub. The production
Cloudflare D1 database is seeded from cf-dashboard-deploy/resources-migration.sql,
which mirrors this list.

Categories: housing, food, clothing, social-services, mental-health
"""
from uuid import uuid5, NAMESPACE_DNS

# Stable IDs derived from name so preview list matches on every restart.
def _rid(name: str) -> str:
    return str(uuid5(NAMESPACE_DNS, f"tryhimandsee-resource:{name}"))

RESOURCES = [
    # -------------------- HOUSING / RENTAL --------------------
    {
        "category": "housing",
        "name": "Homeless Connection Line (Homeward)",
        "description": "Central intake for emergency shelter, outreach and assessments across the Richmond region. Start here if you or someone you know is homeless or facing homelessness within the next 3 days.",
        "address": "9211 Forest Hill Ave, Suite 110, Richmond, VA 23235",
        "phone": "(804) 972-0813",
        "website": "https://www.homewardva.org/get-help",
        "hours": "Mon–Fri 8am–9pm (closed 12–1pm); Sat–Sun 1pm–9pm",
        "notes": "Also managed: Housing Resource Line 804-422-5061 for rental assistance and eviction prevention.",
    },
    {
        "category": "housing",
        "name": "CARITAS Men's Shelter",
        "description": "36-bed emergency shelter for men. Intake via the Homeless Connection Line.",
        "address": "700 Dinwiddie Ave, Richmond, VA 23224",
        "phone": "(804) 887-1598",
        "website": "https://caritasva.org/shelter/",
        "hours": "Intake by referral only",
        "notes": "Call 804-972-0813 (Homeless Connection Line) first.",
    },
    {
        "category": "housing",
        "name": "CARITAS Women's Shelter",
        "description": "28-bed emergency shelter for women. Open 24/7; intake via the Homeless Connection Line.",
        "address": "2220 Stockton St, Richmond, VA 23224",
        "phone": "(804) 343-7277",
        "website": "https://caritasva.org/shelter/",
        "hours": "Open 24/7 by referral",
        "notes": "Call 804-972-0813 first.",
    },
    {
        "category": "housing",
        "name": "Housing Families First",
        "description": "Family-focused housing crisis services, shelter and rapid re-housing in Henrico.",
        "address": "3900 Nine Mile Rd, Henrico, VA 23223",
        "phone": "(804) 236-5800",
        "website": "https://housingfamiliesfirst.org/get-help/",
        "hours": "Mon–Fri, business hours",
        "notes": "Serves families with children.",
    },
    {
        "category": "housing",
        "name": "Home Again",
        "description": "Shelter and re-housing programs for individuals and families.",
        "address": "5 E. Franklin St, Richmond, VA 23219",
        "phone": "(804) 782-9778",
        "website": "https://homeagainrva.org/",
        "hours": "Mon–Fri, business hours",
        "notes": "Intake through the Homeless Connection Line.",
    },
    {
        "category": "housing",
        "name": "Better Housing Coalition",
        "description": "Housing counseling, credit repair and affordable housing for families and seniors.",
        "address": "300 S Randolph St, Richmond, VA 23220",
        "phone": "(804) 354-9455",
        "website": "https://www.betterhousingcoalition.org/",
        "hours": "Mon–Fri 9am–5pm",
        "notes": "",
    },
    {
        "category": "housing",
        "name": "Salvation Army of Central Virginia",
        "description": "Emergency financial aid (EFSP) for rent, security deposits and utilities.",
        "address": "2 W. Grace St, Richmond, VA 23220",
        "phone": "(804) 225-7470",
        "website": "https://southernusa.salvationarmy.org/centralvirginia/",
        "hours": "Mon–Fri, call for appointment",
        "notes": "",
    },
    {
        "category": "housing",
        "name": "Interfaith Services of Henrico County",
        "description": "Emergency rental assistance and grants for Henrico residents in crisis.",
        "address": "8600 Dixon Powers Dr, Henrico, VA 23228",
        "phone": "(804) 285-5986",
        "website": "https://www.interfaithhenrico.org/",
        "hours": "Mon–Fri, call for appointment",
        "notes": "Henrico residents only.",
    },
    {
        "category": "housing",
        "name": "Commonwealth Catholic Charities",
        "description": "HOPWA housing subsidies, rental assistance and case management.",
        "address": "1601 Rolling Hills Dr, Richmond, VA 23229",
        "phone": "(804) 285-5900",
        "website": "https://www.cccofva.org/",
        "hours": "Mon–Fri 9am–5pm",
        "notes": "",
    },
    {
        "category": "housing",
        "name": "Central Virginia Legal Aid Society",
        "description": "Free legal advice for eviction, housing and consumer issues.",
        "address": "101 W Broad St, Richmond, VA 23220",
        "phone": "(804) 648-1012",
        "website": "https://cvlas.org/",
        "hours": "Mon–Fri 9am–5pm",
        "notes": "Eviction Help Line: 1-833-663-8428.",
    },

    # -------------------- FOOD --------------------
    {
        "category": "food",
        "name": "Feed More",
        "description": "Central Virginia's food bank hub. Use their agency locator to find pantries and meal sites near you.",
        "address": "4103 Monument Ave, Richmond, VA 23230",
        "phone": "(804) 471-3713",
        "website": "https://feedmore.org/agency-locator/",
        "hours": "Client pantry: Tuesdays 11am–2pm",
        "notes": "Hunger Hotline: 804-521-2500 (Mon–Fri 8am–4pm).",
    },
    {
        "category": "food",
        "name": "Henrico Community Food Bank",
        "description": "Home food delivery available to all Henrico residents - call to schedule.",
        "address": "PO Box 6300, Glen Allen, VA 23058",
        "phone": "(804) 549-6609",
        "website": "https://henricofoodbank.org/",
        "hours": "Delivery by appointment",
        "notes": "",
    },
    {
        "category": "food",
        "name": "CAPUP North Food Pantry",
        "description": "Full-service food pantry serving Richmond residents.",
        "address": "1021 Oliver Hill Way, Richmond, VA 23219",
        "phone": "(804) 788-0050",
        "website": "https://www.cccofva.org/",
        "hours": "Mon–Thu 10am–1pm",
        "notes": "",
    },
    {
        "category": "food",
        "name": "St. Mark's Episcopal Church Food Pantry",
        "description": "Free groceries - no ID required.",
        "address": "520 N Arthur Ashe Blvd, Richmond, VA 23230",
        "phone": "(804) 358-4771",
        "website": "https://stmarksrva.org/",
        "hours": "2nd & 4th Saturday, 9am–10am",
        "notes": "No ID or paperwork required.",
    },
    {
        "category": "food",
        "name": "Second Baptist Church Food Pantry",
        "description": "Weekly food pantry serving the Idlewood/Randolph community.",
        "address": "1400 Idlewood Ave, Richmond, VA 23220",
        "phone": "(804) 353-7682",
        "website": "",
        "hours": "Wednesdays 9am–1pm",
        "notes": "",
    },
    {
        "category": "food",
        "name": "Sixth Mount Zion Baptist Church",
        "description": "Weekly Friday food distribution.",
        "address": "14 W Duval St, Richmond, VA 23220",
        "phone": "(804) 648-7511",
        "website": "https://smzbc.org/",
        "hours": "Fridays 12pm–1pm",
        "notes": "",
    },
    {
        "category": "food",
        "name": "Lamb's Basket",
        "description": "Food pantry and community outreach in western Henrico.",
        "address": "8419 Oakview Ave, Henrico, VA 23228",
        "phone": "(804) 565-8007",
        "website": "https://www.lambsbasket.org/",
        "hours": "Call for current hours",
        "notes": "",
    },
    {
        "category": "food",
        "name": "Atlantic Outreach Group",
        "description": "Mobile pantry and on-site distribution.",
        "address": "4411 Jacque St, Richmond, VA 23230",
        "phone": "(804) 308-2648",
        "website": "https://aog4u.org/food-pantry/",
        "hours": "Tue 12:30pm mobile; Wed & Fri 12pm–3pm by appointment",
        "notes": "",
    },
    {
        "category": "food",
        "name": "Gayton Baptist Church Food Pantry",
        "description": "Weekly food pantry in western Henrico.",
        "address": "13501 N. Gayton Rd, Henrico, VA 23233",
        "phone": "(804) 476-0632",
        "website": "https://gaytonbaptist.org/",
        "hours": "Tuesdays 12:30pm–1:30pm",
        "notes": "",
    },
    {
        "category": "food",
        "name": "Islamic Center of Henrico Food Pantry",
        "description": "Community food distribution open to all faiths.",
        "address": "3009 Lafayette Ave, Henrico, VA 23228",
        "phone": "(866) 354-0102 ext. 1613",
        "website": "https://icnarelief.org/",
        "hours": "2nd & 4th Sat 11am–1pm; Tue & Thu 4pm–6pm",
        "notes": "",
    },
    {
        "category": "food",
        "name": "Fishes and Loaves Food Pantry",
        "description": "Twice-monthly food distribution in eastern Richmond.",
        "address": "2696 Williamsburg Rd, Richmond, VA 23231",
        "phone": "(804) 222-2612",
        "website": "",
        "hours": "2nd & 4th Sat 10am–12pm",
        "notes": "",
    },
    {
        "category": "food",
        "name": "Varina Episcopal Food Pantry",
        "description": "Bi-weekly evening food pantry.",
        "address": "2385 Mill Rd, Richmond, VA 23231",
        "phone": "(804) 859-0817",
        "website": "",
        "hours": "1st & 3rd Mon 5pm–6pm",
        "notes": "",
    },

    # -------------------- CLOTHING --------------------
    {
        "category": "clothing",
        "name": "Eastern Henrico FISH Clothes Closet",
        "description": "Free clothing for individuals and families in Henrico.",
        "address": "1440 N Laburnum Ave, Richmond, VA 23223",
        "phone": "(804) 257-7730",
        "website": "https://easternhenricofish.org/",
        "hours": "Mon, Wed, Thu 8am–2pm",
        "notes": "",
    },
    {
        "category": "clothing",
        "name": "Belmont Community Resource Services - The Closet",
        "description": "Free clothing and food distribution - South Richmond.",
        "address": "3510 Broad Rock Blvd, Richmond, VA 23234",
        "phone": "(804) 275-6336",
        "website": "https://bcrsrva.org/the-closet/",
        "hours": "Fridays 9am–1pm",
        "notes": "",
    },
    {
        "category": "clothing",
        "name": "The Caring Closet",
        "description": "Free clothes, shoes, sleeping bags and hygiene items.",
        "address": "3900 W Broad St, Cottage 7, Richmond, VA 23230",
        "phone": "(804) 533-2657",
        "website": "https://www.caring-closet.org/",
        "hours": "By appointment",
        "notes": "",
    },
    {
        "category": "clothing",
        "name": "Shady Grove UMC Caring Clothes Closet",
        "description": "Free clothing - appointment only.",
        "address": "4825 Pouncey Tract Rd, Glen Allen, VA 23059",
        "phone": "(804) 360-7779",
        "website": "https://www.shadygroveumc.net/",
        "hours": "By appointment",
        "notes": "",
    },
    {
        "category": "clothing",
        "name": "Our Lady of Lourdes - Laura's Closet",
        "description": "Free clothing distribution weekly.",
        "address": "8200 Woodman Rd, Henrico, VA 23228",
        "phone": "(804) 262-7315",
        "website": "https://ollrichmond.org/",
        "hours": "Tuesdays 9am–10:30am",
        "notes": "",
    },
    {
        "category": "clothing",
        "name": "St. Peter's Catholic Church",
        "description": "Free clothing and shower services.",
        "address": "800 E Grace St, Richmond, VA 23220",
        "phone": "(804) 643-4315",
        "website": "https://saintpetersparish.org/",
        "hours": "Tuesdays 1pm–3:30pm",
        "notes": "",
    },
    {
        "category": "clothing",
        "name": "Dress for Success Central Virginia",
        "description": "Professional attire and career coaching for women returning to work.",
        "address": "210 E Clay St, Richmond, VA 23219",
        "phone": "(804) 234-3034",
        "website": "https://centralvirginia.dressforsuccess.org/",
        "hours": "Mon–Fri by appointment",
        "notes": "Referral usually required.",
    },
    {
        "category": "clothing",
        "name": "Mercy Mall of Virginia",
        "description": "Free clothing closet for the homeless and low-income families, plus low-cost thrift.",
        "address": "7519 Whitepine Rd, Richmond, VA 23237",
        "phone": "(804) 728-2928",
        "website": "https://mercymallva.org/",
        "hours": "Call for hours",
        "notes": "",
    },
    {
        "category": "clothing",
        "name": "Ginter Park United Methodist Church",
        "description": "Community clothes closet.",
        "address": "1010 W Laburnum Ave, Richmond, VA 23227",
        "phone": "(804) 262-8651",
        "website": "https://ginterparkumc.com/",
        "hours": "Call for hours",
        "notes": "",
    },

    # -------------------- SOCIAL SERVICES --------------------
    {
        "category": "social-services",
        "name": "City of Richmond DSS - Downtown Main Office",
        "description": "SNAP, TANF, Medicaid, General Relief and child services for Richmond residents.",
        "address": "300 E. Franklin St, Richmond, VA 23219",
        "phone": "(804) 646-7212",
        "website": "https://www.rva.gov/social-services",
        "hours": "Mon–Fri 8am–5pm",
        "notes": "Call 3-1-1 within Richmond.",
    },
    {
        "category": "social-services",
        "name": "City of Richmond DSS - South Richmond",
        "description": "Child services and economic support (SNAP/TANF) for South Richmond.",
        "address": "4100 Hull Street Rd, Richmond, VA 23224",
        "phone": "(804) 646-8800",
        "website": "https://www.rva.gov/social-services",
        "hours": "Mon–Fri 8am–5pm",
        "notes": "",
    },
    {
        "category": "social-services",
        "name": "City of Richmond DSS - East Richmond",
        "description": "Child services and economic support for East Richmond.",
        "address": "701 N 25th St, Richmond, VA 23223",
        "phone": "(804) 646-7320",
        "website": "https://www.rva.gov/social-services",
        "hours": "Mon–Fri 8am–5pm",
        "notes": "",
    },
    {
        "category": "social-services",
        "name": "Henrico County DSS - West End (Main)",
        "description": "SNAP, TANF, Medicaid and full social services for Henrico residents.",
        "address": "8600 Dixon Powers Dr, Henrico, VA 23228",
        "phone": "(804) 501-4001",
        "website": "https://henrico.gov/dss/",
        "hours": "Mon–Fri 8am–4:30pm",
        "notes": "Fax applications: 804-501-4006.",
    },
    {
        "category": "social-services",
        "name": "Henrico County DSS - East End",
        "description": "Benefit programs only (SNAP, TANF).",
        "address": "3820 Nine Mile Rd, Henrico, VA 23223",
        "phone": "(804) 652-3123",
        "website": "https://henrico.gov/dss/",
        "hours": "Mon–Fri 8am–4:30pm",
        "notes": "",
    },
    {
        "category": "social-services",
        "name": "CommonHelp - Statewide Benefits Portal",
        "description": "Online application for SNAP, TANF, Medicaid and energy assistance across Virginia.",
        "address": "Online / Statewide",
        "phone": "(855) 635-4370",
        "website": "https://www.commonhelp.virginia.gov",
        "hours": "24/7 online",
        "notes": "Call center: Mon–Fri.",
    },
    {
        "category": "social-services",
        "name": "211 Virginia",
        "description": "Statewide referral line - dial 2-1-1 for help with food, housing, utilities, healthcare and more.",
        "address": "Statewide",
        "phone": "2-1-1",
        "website": "https://www.211virginia.org/",
        "hours": "24/7",
        "notes": "",
    },
    {
        "category": "social-services",
        "name": "Family Lifeline",
        "description": "Home visiting, senior services, and central hunger/resource hotline.",
        "address": "Serving Richmond & Henrico",
        "phone": "(804) 521-2500",
        "website": "https://www.familylifeline.org/resource-hub",
        "hours": "Mon–Fri 8am–4pm",
        "notes": "",
    },
    {
        "category": "social-services",
        "name": "Society of St. Vincent de Paul (Richmond Council)",
        "description": "Emergency financial aid - rent, utilities, security deposits - in select zip codes.",
        "address": "4491 Springfield Rd, Glen Allen, VA 23060",
        "phone": "(804) 997-4489",
        "website": "https://svdp-rvacouncil.org/",
        "hours": "By phone intake",
        "notes": "",
    },

    # -------------------- MENTAL / BEHAVIORAL HEALTH --------------------
    {
        "category": "mental-health",
        "name": "988 Suicide & Crisis Lifeline",
        "description": "Free 24/7 confidential support for anyone in emotional distress or crisis. Call or text 988.",
        "address": "Nationwide",
        "phone": "988",
        "website": "https://988lifeline.org/",
        "hours": "24/7",
        "notes": "Text HOME to 741741 for Crisis Text Line.",
    },
    {
        "category": "mental-health",
        "name": "Richmond Behavioral Health Authority (RBHA) - 24/7 Crisis",
        "description": "24-hour behavioral health crisis line for Richmond City residents. Walk-in assessments available on weekdays.",
        "address": "107 S. 5th Street, Richmond, VA 23219",
        "phone": "(804) 819-4100",
        "website": "https://www.rbha.org/services/crisis-response.aspx",
        "hours": "Crisis line 24/7; walk-in Mon–Fri 8am–2pm",
        "notes": "Main line: 804-819-4000.",
    },
    {
        "category": "mental-health",
        "name": "Henrico Area Mental Health & Developmental Services (HAMHDS) - 24/7 Crisis",
        "description": "24-hour crisis line for Henrico, Charles City and New Kent residents. Crisis stabilization, outpatient and pre-screening.",
        "address": "10299 Woodman Rd, Glen Allen, VA 23060",
        "phone": "(804) 727-8484",
        "website": "https://henrico.gov/mhds/",
        "hours": "Crisis line 24/7",
        "notes": "Non-crisis intake: 804-727-8500.",
    },
    {
        "category": "mental-health",
        "name": "HAMHDS - East Center",
        "description": "Outpatient behavioral health services for East Henrico.",
        "address": "3908 Nine Mile Rd, Henrico, VA 23223",
        "phone": "(804) 727-8484",
        "website": "https://henrico.gov/mhds/",
        "hours": "Mon–Fri, business hours",
        "notes": "",
    },
    {
        "category": "mental-health",
        "name": "Adult Regional Crisis Services (Region 4)",
        "description": "Adult regional crisis line covering Chesterfield, Richmond, Henrico and Hanover.",
        "address": "Regional",
        "phone": "(855) 282-1006",
        "website": "https://www.rbha.org/services/crisis-response/adult-regional-crisis-services.aspx",
        "hours": "24/7 crisis line",
        "notes": "Referral line: 833-968-1800.",
    },
    {
        "category": "mental-health",
        "name": "Crisis Receiving Center - St. Joseph's Villa",
        "description": "Emergency behavioral health center for youth across Central Virginia.",
        "address": "8000 Brook Road, Richmond, VA 23227",
        "phone": "(804) 553-3201",
        "website": "https://neverstopbelieving.org/services/",
        "hours": "24/7 youth crisis",
        "notes": "",
    },
    {
        "category": "mental-health",
        "name": "Sheltering Arms Institute - Behavioral Health",
        "description": "Outpatient mental health services and referrals.",
        "address": "2000 Westmoreland St, Richmond, VA 23230",
        "phone": "(804) 764-1000",
        "website": "https://shelteringarmsinstitute.com/",
        "hours": "Mon–Fri, business hours",
        "notes": "",
    },
    {
        "category": "mental-health",
        "name": "NAMI Central Virginia",
        "description": "Peer-led support groups, education classes and family support for mental illness.",
        "address": "PO Box 12245, Richmond, VA 23241",
        "phone": "(804) 285-1749",
        "website": "https://namicentralvirginia.org/",
        "hours": "Mon–Fri, business hours",
        "notes": "",
    },

    # -------------------- ABUSE / DOMESTIC VIOLENCE --------------------
    {
        "category": "domestic-violence",
        "name": "Greater Richmond Regional Hotline (YWCA)",
        "description": "24/7 confidential crisis line for domestic and sexual violence - serving Richmond, Henrico, and Chesterfield. Managed by YWCA, routes callers to Safe Harbor and other partners for emergency shelter, safety planning, and counseling.",
        "address": "Serving Richmond & Henrico",
        "phone": "(804) 612-6126",
        "website": "https://ywcarichmond.org/get-help/",
        "hours": "24 hours, 7 days a week",
        "notes": "If you are in immediate danger, call 911 first. Text-capable line.",
    },
    {
        "category": "domestic-violence",
        "name": "YWCA of Richmond - Domestic Violence Services",
        "description": "Emergency shelter, crisis counseling, court advocacy, and support groups for survivors of domestic and sexual violence.",
        "address": "6 N. Fifth St, Richmond, VA 23219",
        "phone": "(804) 643-6761",
        "website": "https://ywcarichmond.org/what-we-do/",
        "hours": "Admin Mon–Fri 9am–5pm; crisis line 24/7 at 804-612-6126",
        "notes": "Services are free and confidential.",
    },
    {
        "category": "domestic-violence",
        "name": "Safe Harbor - 24/7 Helpline",
        "description": "24-hour crisis hotline for domestic and sexual violence survivors in Henrico County and Richmond. Access to emergency shelter, safety planning, and advocacy.",
        "address": "Serving Henrico & Richmond",
        "phone": "(804) 500-2755",
        "website": "https://safeharborshelter.com/",
        "hours": "24 hours, 7 days a week",
        "notes": "Confidential - shelter location is not disclosed publicly for safety.",
    },
    {
        "category": "domestic-violence",
        "name": "Safe Harbor - Administrative & Counseling Office",
        "description": "Non-crisis appointments, counseling, court advocacy, and prevention education.",
        "address": "1934 N. Parham Rd, Suite 300, Henrico, VA 23229",
        "phone": "(804) 249-9470",
        "website": "https://safeharborshelter.com/contact/",
        "hours": "Mon–Fri, business hours",
        "notes": "For 24-hour crisis, call 804-500-2755.",
    },
    {
        "category": "domestic-violence",
        "name": "Henrico Police - Domestic Violence Victim Services",
        "description": "Confidential support, safety planning, and criminal-justice advocacy for Henrico County domestic violence victims. Assistance with protective orders.",
        "address": "7721 E. Parham Rd, Henrico, VA 23294",
        "phone": "(804) 501-4830",
        "website": "https://henrico.gov/police/crime-prevention/domestic-violence-assistance/",
        "hours": "Mon–Fri 8am–4:30pm",
        "notes": "Call 911 if in immediate danger.",
    },
    {
        "category": "domestic-violence",
        "name": "Richmond Police - Family & Sexual Violence Unit",
        "description": "Specialized investigators for domestic and sexual violence within Richmond City. Coordinates with victim advocates and shelters.",
        "address": "200 W Grace St, Richmond, VA 23220",
        "phone": "(804) 646-3011",
        "website": "https://www.rva.gov/police",
        "hours": "24/7 dispatch - call 911 for emergencies",
        "notes": "Non-emergency: dial 3-1-1 within Richmond.",
    },
    {
        "category": "domestic-violence",
        "name": "Virginia Statewide Hotline (Action Alliance)",
        "description": "Statewide bilingual hotline (English/Spanish) for domestic and sexual violence - free, confidential, 24/7. Text and chat options available.",
        "address": "Statewide",
        "phone": "1 (800) 838-8238",
        "website": "https://vadata.org/",
        "hours": "24/7",
        "notes": "Text: 804-793-9999. Chat at vadata.org.",
    },
    {
        "category": "domestic-violence",
        "name": "National Domestic Violence Hotline",
        "description": "24/7 confidential support in 200+ languages. Text, call, or chat with trained advocates for safety planning and referrals.",
        "address": "Nationwide",
        "phone": "1 (800) 799-7233",
        "website": "https://www.thehotline.org/",
        "hours": "24/7",
        "notes": "Text START to 88788. Deaf/hard of hearing: video call via thehotline.org.",
    },
    {
        "category": "domestic-violence",
        "name": "Central Virginia Legal Aid Society - Protective Orders",
        "description": "Free civil legal help for survivors of domestic violence - protective orders, custody, divorce, and eviction defense.",
        "address": "101 W Broad St, Richmond, VA 23220",
        "phone": "(804) 648-1012",
        "website": "https://cvlas.org/",
        "hours": "Mon–Fri 9am–5pm",
        "notes": "Intake by phone - ask for the domestic violence advocate.",
    },
    {
        "category": "domestic-violence",
        "name": "Richmond SPCA - Safer Together (SAAF) Program",
        "description": "Free foster care for pets of domestic violence survivors entering shelter - so no one has to choose between safety and their beloved companion.",
        "address": "2519 Hermitage Rd, Richmond, VA 23220",
        "phone": "(804) 521-1330",
        "website": "https://richmondspca.org/saaf-providing-a-safe-harbor-for-family-pets-at-a-time-of-critical-need/",
        "hours": "Mon–Sun, by referral through YWCA/Safe Harbor",
        "notes": "Confidential - coordinated via 804-612-6126.",
    },
]

# Return list with derived stable ids and category-based ordering.
def get_seed_resources():
    for idx, r in enumerate(RESOURCES):
        yield {
            "id": _rid(r["name"]),
            **r,
            "sort_order": idx,
            "is_active": 1,
        }
